#version: '3.1'

services:
  mysql-db:
    image: mysql:8.4.2
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phonebook # Nazwa domyślnej bazy danych
      MYSQL_USER: phonebook_user  # Nazwa użytkownika
      MYSQL_PASSWORD: 123456
    ports:
      - "33061:3306"